- project:
    name: disa/disa-docs
    check:
      jobs:
        - linters
        - build-sphinx-docs:
            success-url: 'html/'
            vars:
              doc_building_packages: "sphinx==1.7.8"
              sphinx_source_dir: "doc"
              sphinx_build_dir: "build"
              sphinx_builders:
                - html
                - spelling

    gate:
      jobs:
        - linters
        - build-sphinx-docs:
            success-url: 'html/'
            vars:
              doc_building_packages: "sphinx==1.7.8"
              sphinx_source_dir: "doc"
              sphinx_build_dir: "build"
              sphinx_builders:
                - html

#    post:
#      jobs:
#        - build-sphinx-docs:
#            success-url: 'singlehtml/'
#            vars:
#              doc_building_packages: "sphinx==1.7.8"
#              sphinx_source_dir: "doc"
#              sphinx_build_dir: "build"
#              sphinx_builders:
#                - singlehtml
#        - freshdesk-doc-upload:
#            dependencies:
#              - build-sphinx-docs
#            vars:
#              article_category: "Netronome Only"
#              article_folder: "Test folder for API development"
#              article_title: "Test Article"
#              article_location: "{{ sphinx_artifacts_url }}/index.html"
