#!/bin/bash

# This is a helper script to provide more consistent netdev
# names for VF and PF representors across reboots. It assumes
# that the least significant bits of the switch ID is unique.

# This script is intended to reside at:
# /lib/udev/switchdev-repr-name-gen

PREFIX=r
MAX_NETDEV_LEN=15
SYSPATH="/sys/class/net/$1"
DEV_ID=$(<"${SYSPATH}/dev_id")
DEV_PORT=$(<"${SYSPATH}/dev_port")
PHYS_PORT_NAME=$(<"${SYSPATH}/phys_port_name")
PHYS_SWITCH_ID=$(<"${SYSPATH}/phys_switch_id")

# The following fields need to be PRESENT
[ -z "${PHYS_PORT_NAME}" ] && exit 0
[ -z "${PHYS_SWITCH_ID}" ] && exit 0
# The following fields need to be ABSENT
[ -z "${ID_NET_NAME_ONBOARD}" ] || exit 0
[ -z "${ID_NET_NAME_SLOT}" ] || exit 0
[ -z "${ID_NET_NAME_PATH}" ] || exit 0

FULL_LEN=$((${#PREFIX} + ${#PHYS_SWITCH_ID} + ${#PHYS_PORT_NAME} + 1))

if [ ${FULL_LEN} -gt ${MAX_NETDEV_LEN} ]; then
    # We need to left-truncate PHYS_SWITCH_ID
    TRUNCATE_LEN=$((${FULL_LEN} - ${MAX_NETDEV_LEN}))
    PHYS_SWITCH_ID=${PHYS_SWITCH_ID:${TRUNCATE_LEN}}
fi

ID_NET_NAME_REPR=${PREFIX}${PHYS_SWITCH_ID}n${PHYS_PORT_NAME}

[ -n "${ID_NET_NAME_REPR}" ] && echo "ID_NET_NAME_REPR=${ID_NET_NAME_REPR}"
