name: Build and Lint

on: push

jobs:
  build:
    name: build lint
    runs-on: ubuntu-20.04
    timeout-minutes: 7

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get -y install make git python3-doc8 python3-pip python3-sphinx-rtd-theme python3-sphinxcontrib.spelling
        sudo pip3 install sphinxcontrib.imageembed
        sphinxpath=`sudo pip3 show sphinxcontrib-imageembed | grep Location | awk '{print $2}'`
        find $sphinxpath -name "imageembed.py" -exec sed -i 's/encoded = base64.b64encode(open(filename, "rb").read())\s*$/encoded = base64.b64encode(open(filename, "rb").read()).decode("ascii")/g' {} \;

    - name: make html
      run: make html

    - name: check spelling
      run: make spelling

    - name: lint
      run: doc8 --ignore-path ./build

    - name: upload html documents
      uses: actions/upload-artifact@v2
      with:
        name: html-docs
        path: './build/html/*'
